// GENERATED by tool/generate_pixel_css.dart - do not edit by hand.
// Regenerate with: dart run tool/generate_pixel_css.dart --dart
//
// Metadata only - the shadow strings live in pixel_art_shadows.dart,
// which is imported *deferred* so dart2js splits it into its own
// part file, downloaded only when the dial approaches AM 1440.
library;

class PixelSprite {
  const PixelSprite({
    required this.id,
    required this.gridW,
    required this.gridH,
    required this.hasGif,
  });

  final String id;
  final int gridW;
  final int gridH;

  /// Every piece has a full-quality reward file under `web/pixel/`,
  /// revealed on completing its puzzle: `<id>.gif` (the animated
  /// original) when this is true, `<id>.png` otherwise.
  final bool hasGif;
}

/// Rail order. The visible identifier pixel-art-N is index + 1.
const pixelArtPieces = <PixelSprite>[
  // assets/pixel-art/ahh real monsters krumm octobit.png (80x63, 5040 px)
  PixelSprite(id: 'krumm', gridW: 80, gridH: 63, hasGif: false),
  // assets/pixel-art/arbol1.png (48x48, 1093 px)
  PixelSprite(id: 'arbol', gridW: 48, gridH: 48, hasGif: false),
  // assets/pixel-art/astronaut octobit.png (126x126 decimated 2x, 3969 px)
  PixelSprite(id: 'astronaut', gridW: 63, gridH: 63, hasGif: true),
  // assets/pixel-art/baby octobit 16.png (32x32, 1024 px)
  PixelSprite(id: 'baby', gridW: 32, gridH: 32, hasGif: true),
  // assets/pixel-art/bad witch octobit-2.png (64x64, 4096 px)
  PixelSprite(id: 'witch', gridW: 64, gridH: 64, hasGif: false),
  // assets/pixel-art/band of broters1.png (126x71 decimated 2x, 2268 px)
  PixelSprite(id: 'brothers', gridW: 63, gridH: 36, hasGif: true),
  // assets/pixel-art/band of brothers 2.png (128x72 decimated 2x, 2304 px)
  PixelSprite(id: 'brothers2', gridW: 64, gridH: 36, hasGif: false),
  // assets/pixel-art/biberon.png (128x128 decimated 2x, 4096 px)
  PixelSprite(id: 'biberon', gridW: 64, gridH: 64, hasGif: false),
  // assets/pixel-art/blanket fort octobit.png (98x55 decimated 2x, 1372 px)
  PixelSprite(id: 'fort', gridW: 49, gridH: 28, hasGif: false),
  // assets/pixel-art/boss demon.png (64x64, 4096 px)
  PixelSprite(id: 'demon', gridW: 64, gridH: 64, hasGif: false),
  // assets/pixel-art/butterflies octobit.png (128x128 decimated 2x, 4096 px)
  PixelSprite(id: 'butterflies', gridW: 64, gridH: 64, hasGif: false),
  // assets/pixel-art/cake octobit3.png (32x32, 1024 px)
  PixelSprite(id: 'cake', gridW: 32, gridH: 32, hasGif: true),
  // assets/pixel-art/carro1.png (59x32, 1888 px)
  PixelSprite(id: 'carro', gridW: 59, gridH: 32, hasGif: true),
  // assets/pixel-art/city.png (180x100 decimated 3x, 2040 px)
  PixelSprite(id: 'city', gridW: 60, gridH: 34, hasGif: false),
  // assets/pixel-art/claustrofobia1.png (64x64, 4096 px)
  PixelSprite(id: 'claustrofobia', gridW: 64, gridH: 64, hasGif: true),
  // assets/pixel-art/cult octobit 18.png (63x64, 4032 px)
  PixelSprite(id: 'cult', gridW: 63, gridH: 64, hasGif: true),
  // assets/pixel-art/haunted tree house octobit #7-2.png (128x129 decimated 2x, 4160 px)
  PixelSprite(id: 'haunted', gridW: 64, gridH: 65, hasGif: false),
  // assets/pixel-art/issues doll octobit clone clone.png (64x64, 4096 px)
  PixelSprite(id: 'doll', gridW: 64, gridH: 64, hasGif: true),
  // assets/pixel-art/killing road trip octobit.png (60x32, 1920 px)
  PixelSprite(id: 'roadtrip', gridW: 60, gridH: 32, hasGif: true),
  // assets/pixel-art/legs octobit.png (128x128 decimated 2x, 4096 px)
  PixelSprite(id: 'legs', gridW: 64, gridH: 64, hasGif: false),
  // assets/pixel-art/monocromatic clone clone.png (240x191 decimated 3x, 5120 px)
  PixelSprite(id: 'mono', gridW: 80, gridH: 64, hasGif: false),
  // assets/pixel-art/mushroom pizza octobit.png (41x37, 1517 px)
  PixelSprite(id: 'pizza', gridW: 41, gridH: 37, hasGif: false),
  // assets/pixel-art/muñequita.png (64x64, 4096 px)
  PixelSprite(id: 'munequita', gridW: 64, gridH: 64, hasGif: false),
  // assets/pixel-art/playground isolation octobit.png (79x82 decimated 2x, 1640 px)
  PixelSprite(id: 'playground', gridW: 40, gridH: 41, hasGif: true),
  // assets/pixel-art/poison soup octobit.png (65x64, 4160 px)
  PixelSprite(id: 'soup', gridW: 65, gridH: 64, hasGif: true),
  // assets/pixel-art/predator octobit.png (64x63, 4032 px)
  PixelSprite(id: 'predator', gridW: 64, gridH: 63, hasGif: true),
  // assets/pixel-art/retrato-00.png (200x158 decimated 3x, 3551 px)
  PixelSprite(id: 'retrato', gridW: 67, gridH: 53, hasGif: false),
  // assets/pixel-art/rotten fresh octobit - 1.png (201x128 decimated 3x, 2881 px)
  PixelSprite(id: 'rotten', gridW: 67, gridH: 43, hasGif: true),
  // assets/pixel-art/sentado mirando clone clone(1).png (200x140 decimated 3x, 3149 px)
  PixelSprite(id: 'sentado', gridW: 67, gridH: 47, hasGif: false),
  // assets/pixel-art/shark1.png (46x64, 2944 px)
  PixelSprite(id: 'shark', gridW: 46, gridH: 64, hasGif: true),
  // assets/pixel-art/sushi rice octobit.png (100x64 decimated 2x, 1600 px)
  PixelSprite(id: 'sushi', gridW: 50, gridH: 32, hasGif: false),
  // assets/pixel-art/theme park octobit2.png (189x127 decimated 3x, 2709 px)
  PixelSprite(id: 'themepark', gridW: 63, gridH: 43, hasGif: false),
  // assets/pixel-art/thorns octobit.png (197x180 decimated 3x, 3960 px)
  PixelSprite(id: 'thorns', gridW: 66, gridH: 60, hasGif: true),
  // assets/pixel-art/clown octobit #1 clone.png (129x129 square-cropped, 16641 px)
  PixelSprite(id: 'clown', gridW: 129, gridH: 129, hasGif: true),
];
